### ISSUE TITLE
Hosted Pages not Supported

### ISSUE THREAD

**Issue by mostekcm** [xurei/auth0-dump-config#1]
This is really awesome that you created this @xurei!  Saved me some effort of doing this myself.  I was wondering whether you skipped hosted pages because you didn't have time to get to it, or if you ran into a technical difficulty.

I've referenced this repo in the auth0-deploy-cli docs!

Thanks,

Carlos

**Comment by xurei** [comment]
Thanks, glad you like it @mostekcm. I'm very proud to be cited in the official docs <3

Actually I didn't find the API endpoint for getting them. If you can point out where it is, I can add the functionnality quite easily.

**Comment by mostekcm** [comment]
The fix to this might be a little involved :).  There isn't a direct "hosted pages" API as of yet.  The pages are stored as settings on the global client.  Each page has a little different way to set it.

I have two recommendations for getting this working.

1) Start using the node-auth0 library.  It may be easiest to do this by pulling in the auth0-source-control-extension-tools (see here: https://github.com/auth0-extensions/auth0-source-control-extension-tools).  If you use those it is easy to initialize a management client for the Management API, see here: https://github.com/auth0/auth0-deploy-cli/blob/master/src/index.js#L105-L111.  With that client it is simple to interact with your settings in Auth0.
2) Once you have the client, see this doc for an example of how we are setting the values for the hosted pages, you can basically do the same to get the values.  The one thing you may run into is that the extension doesn't set the right scope, you may be missing the read:tenant_settings scope.  If you find that is true, let me know and I can add that scope to the extension.  In the mean time, you can do it manually by altering your client grants (see the deploy CLI readme for instructions).  Here is the file you should use for examples for how to interact with the management client.  In this file the "client" is the management client: https://github.com/auth0-extensions/auth0-source-control-extension-tools/blob/master/src/auth0/pages.js

Good luck!  Let me know if you have more questions.
