### ISSUE TITLE
Does not get Resource servers 

### ISSUE THREAD

**Issue by jeson114** [xurei/auth0-dump-config#9]
This plugin does not get my Auth0 apis , i had to manually extend this plugin to add that behaviour . 
Is this is a bug or am i missing something since the README mentions the directory structure which includes resource-servers

**Comment by fyockm** [comment]
@jeson114 the `export` functionality just added to [auth0-deploy-cli](https://github.com/auth0/auth0-deploy-cli#cli-options) will handle resource-servers. `auth0-dump-config` will soon be deprecated.
